import json
from pathlib import Path


ATTACK_MAP = {
	"Dangerous eval() usage": {
		"attack_type": "Remote Code Execution",
		"success_probability": "High",
		"mitre": "T1059",
		"impact": "Attacker may execute arbitrary system commands.",
		"explanation": (
			"Untrusted input is passed directly into eval(), which executes it as code.\n"
			"An attacker can inject their own Python instructions to run on the server.\n"
			"This can lead to system takeover, data theft, or unauthorized access.\n"
			"Avoid eval() with user input and use safe parsing instead."
		),
		"attack_path": [
			"Inject malicious payload",
			"Execute arbitrary Python code",
			"Gain server access",
			"Exfiltrate sensitive data",
		],
	},
	"Hardcoded Password": {
		"attack_type": "Credential Abuse",
		"success_probability": "High",
		"mitre": "T1110",
		"impact": "Attacker may gain unauthorized access using exposed credentials.",
		"explanation": (
			"A real password is stored directly in the source code.\n"
			"If the repository is leaked or shared, attackers can read it easily.\n"
			"Those credentials can then be used to access protected systems.\n"
			"Store secrets in environment variables or a secret manager instead."
		),
		"attack_path": [
			"Obtain hardcoded password",
			"Attempt login with exposed credential",
			"Access protected resources",
			"Expand access privileges",
		],
	},
	"Hardcoded API Key": {
		"attack_type": "Credential Abuse",
		"success_probability": "Medium",
		"mitre": "T1552",
		"impact": "Attacker may access external services and data via the exposed API key.",
		"explanation": (
			"An API key is embedded in the code instead of stored securely.\n"
			"Anyone with access to the repository can reuse the key.\n"
			"Attackers may abuse external services and access sensitive data.\n"
			"Move keys to environment variables and rotate exposed keys."
		),
		"attack_path": [
			"Extract API key from source",
			"Authenticate to external service",
			"Access data or perform actions",
			"Pivot to additional systems",
		],
	},
	"SQL Injection Risk": {
		"attack_type": "Database Exploitation",
		"success_probability": "High",
		"mitre": "T1190",
		"impact": "Attacker may read or modify sensitive database records.",
		"explanation": (
			"User input is directly concatenated into an SQL query.\n"
			"Attackers can inject their own SQL to change the query logic.\n"
			"This can expose private data or allow data modification.\n"
			"Use parameterized queries or ORM bindings to prevent injection."
		),
		"attack_path": [
			"Inject crafted SQL payload",
			"Bypass input validation",
			"Read or modify database rows",
			"Exfiltrate sensitive data",
		],
	},
	"Dangerous os.system() usage": {
		"attack_type": "Command Injection",
		"success_probability": "High",
		"mitre": "T1059",
		"impact": "Attacker may execute system commands on the host.",
		"explanation": (
			"User input is executed directly as a system command.\n"
			"Attackers can append their own shell commands to run on the host.\n"
			"This may lead to server compromise or data theft.\n"
			"Avoid shell execution or strictly validate and escape inputs."
		),
		"attack_path": [
			"Inject command payload",
			"Execute system command",
			"Gain host access",
			"Persist or exfiltrate data",
		],
	},
	"Unsafe subprocess usage": {
		"attack_type": "Command Injection",
		"success_probability": "High",
		"mitre": "T1059",
		"impact": "Attacker may execute arbitrary commands via shell invocation.",
		"explanation": (
			"The code runs subprocesses with shell=True while using external input.\n"
			"This allows attackers to inject extra shell commands.\n"
			"Those commands run with the application's permissions.\n"
			"Disable shell execution and pass arguments safely as a list."
		),
		"attack_path": [
			"Supply malicious argument",
			"Trigger subprocess with shell",
			"Execute system command",
			"Escalate or move laterally",
		],
	},
}

DEFAULT_EXPLANATION = (
	"This issue indicates a risky coding pattern was detected.\n"
	"Attackers may use it to access data or execute unintended actions.\n"
	"The exact impact depends on how the code is reached at runtime.\n"
	"Review the code path and apply secure coding practices."
)


def load_scan_results() -> dict:
	"""Load scanner_output.json generated by the Scanner Agent."""
	output_path = Path(__file__).parent / "scanner_output.json"
	try:
		with output_path.open("r", encoding="utf-8") as handle:
			return json.load(handle)
	except (OSError, json.JSONDecodeError):
		return {"repository": "unknown", "findings": []}


def analyze_attacks(scan_data: dict) -> dict:
	"""Analyze vulnerabilities and return simulated attack analysis."""
	repository = scan_data.get("repository", "unknown")
	results = {"repository": repository, "attack_analysis": []}

	for finding in scan_data.get("findings", []):
		vuln_name = finding.get("vulnerability", "Unknown")
		entry = ATTACK_MAP.get(vuln_name)
		if entry:
			results["attack_analysis"].append(
				{
					"id": finding.get("id", ""),
					"file": finding.get("file", ""),
					"line": finding.get("line", 0),
					"vulnerability": vuln_name,
					"human_readable_explanation": entry.get("explanation", DEFAULT_EXPLANATION),
					"attack_type": entry["attack_type"],
					"severity": finding.get("severity", "Unknown"),
					"cwe": finding.get("cwe", "CWE-000"),
					"exploitability": finding.get("exploitability", 0.0),
					"success_probability": entry["success_probability"],
					"mitre_technique": entry["mitre"],
					"impact": entry["impact"],
					"attack_path": entry["attack_path"],
					"code_snippet": finding.get("code_snippet", ""),
				}
			)
		else:
			results["attack_analysis"].append(
				{
					"id": finding.get("id", ""),
					"file": finding.get("file", ""),
					"line": finding.get("line", 0),
					"vulnerability": vuln_name,
					"human_readable_explanation": DEFAULT_EXPLANATION,
					"attack_type": "Unknown",
					"severity": finding.get("severity", "Unknown"),
					"cwe": finding.get("cwe", "CWE-000"),
					"exploitability": finding.get("exploitability", 0.0),
					"success_probability": "Unknown",
					"mitre_technique": "Unknown",
					"impact": "No impact mapping available.",
					"attack_path": ["No simulated attack path available"],
					"code_snippet": finding.get("code_snippet", ""),
				}
			)

	return results


def save_attack_results(attack_results: dict) -> None:
	"""Save attack results to attack_output.json for frontend use."""
	output_path = Path(__file__).parent / "attack_output.json"
	try:
		with output_path.open("w", encoding="utf-8") as handle:
			json.dump(attack_results, handle, indent=2)
	except OSError:
		return


if __name__ == "__main__":
	output = analyze_attacks(load_scan_results())
	save_attack_results(output)
	print(json.dumps(output, indent=2))
